### ISSUE TITLE
Bump ocd_datalake_rs dependency to v0.2.0

### ISSUE THREAD

**Issue by Hugo-C** [cert-orangecyberdefense/datalake-hunter#27]
We should bump the library version to [v0.2.0](https://github.com/cert-orangecyberdefense/ocd-datalake-rs/releases/tag/v0.2.0) to benefit from the auto refresh of Datalake tokens.

**Comment by mrtnhwtt** [comment]
Version was updated in datalake_hunter release 0.1.2.
